import type { Question } from "./types";

export const defaultBattleQuestions: Question[] = [
  {
    id: "forest-1",
    prompt: "Which data structure follows First-In, First-Out order?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    answerIndex: 1,
    category: "Computer Science",
  },
  {
    id: "forest-2",
    prompt: "What is the capital city of Japan?",
    options: ["Seoul", "Kyoto", "Tokyo", "Osaka"],
    answerIndex: 2,
    category: "Geography",
  },
  {
    id: "forest-3",
    prompt: "Which planet is known as the Red Planet?",
    options: ["Mars", "Venus", "Mercury", "Jupiter"],
    answerIndex: 0,
    category: "Science",
  },
  {
    id: "forest-4",
    prompt: "What does CSS stand for?",
    options: [
      "Creative Style Sheets",
      "Cascading Style Sheets",
      "Computer Styled Syntax",
      "Colorful Sheet System",
    ],
    answerIndex: 1,
    category: "Web",
  },
  {
    id: "forest-5",
    prompt: "Which number is a prime number?",
    options: ["21", "27", "29", "33"],
    answerIndex: 2,
    category: "Math",
  },
  {
    id: "forest-6",
    prompt: "Who wrote 'Romeo and Juliet'?",
    options: [
      "William Shakespeare",
      "Charles Dickens",
      "Jane Austen",
      "Mark Twain",
    ],
    answerIndex: 0,
    category: "Literature",
  },
  {
    id: "forest-7",
    prompt: "What is the result of 9 x 7?",
    options: ["56", "63", "72", "81"],
    answerIndex: 1,
    category: "Math",
  },
  {
    id: "forest-8",
    prompt: "Which gas do humans breathe in to survive?",
    options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    answerIndex: 2,
    category: "Science",
  },
  {
    id: "forest-9",
    prompt: "Which HTML tag is used for the largest heading by default?",
    options: ["<heading>", "<h6>", "<h1>", "<header>"],
    answerIndex: 2,
    category: "Web",
  },
  {
    id: "forest-10",
    prompt: "What is the boiling point of water at sea level?",
    options: ["90°C", "100°C", "110°C", "120°C"],
    answerIndex: 1,
    category: "Science",
  },
  {
    id: "forest-11",
    prompt: "Which sorting algorithm repeatedly swaps adjacent out-of-order elements?",
    options: [
      "Merge sort",
      "Quick sort",
      "Bubble sort",
      "Heap sort",
    ],
    answerIndex: 2,
    category: "Computer Science",
  },
  {
    id: "forest-12",
    prompt: "Which ocean is the largest on Earth?",
    options: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"],
    answerIndex: 2,
    category: "Geography",
  },
  {
    id: "forest-13",
    prompt: "What does CPU stand for?",
    options: [
      "Central Processing Unit",
      "Computer Power Utility",
      "Central Program Usage",
      "Control Processing User",
    ],
    answerIndex: 0,
    category: "Computer Science",
  },
  {
    id: "forest-14",
    prompt: "Which country is famous for the city of Cairo?",
    options: ["Egypt", "Turkey", "Morocco", "Greece"],
    answerIndex: 0,
    category: "Geography",
  },
  {
    id: "forest-15",
    prompt: "What is 15 + 27?",
    options: ["40", "41", "42", "43"],
    answerIndex: 2,
    category: "Math",
  },
  {
    id: "forest-16",
    prompt: "Which part of the plant usually absorbs water from soil?",
    options: ["Leaf", "Flower", "Stem", "Root"],
    answerIndex: 3,
    category: "Science",
  },
  {
    id: "forest-17",
    prompt: "Which language is primarily used to style web pages?",
    options: ["HTML", "CSS", "SQL", "Python"],
    answerIndex: 1,
    category: "Web",
  },
  {
    id: "forest-18",
    prompt: "Who is the author of 'Pride and Prejudice'?",
    options: [
      "Emily Bronte",
      "Jane Austen",
      "Mary Shelley",
      "Virginia Woolf",
    ],
    answerIndex: 1,
    category: "Literature",
  },
  {
    id: "forest-19",
    prompt: "Which number is divisible by both 2 and 3?",
    options: ["14", "18", "25", "27"],
    answerIndex: 1,
    category: "Math",
  },
  {
    id: "forest-20",
    prompt: "What do bees primarily collect from flowers?",
    options: ["Nectar", "Sand", "Dew", "Bark"],
    answerIndex: 0,
    category: "Science",
  },
  {
    id: "forest-21",
    prompt: "Which HTML tag is commonly used to create a hyperlink?",
    options: ["<link>", "<a>", "<p>", "<href>"],
    answerIndex: 1,
    category: "Web",
  },
  {
    id: "forest-22",
    prompt: "Which continent is Brazil located in?",
    options: ["Africa", "Europe", "South America", "Asia"],
    answerIndex: 2,
    category: "Geography",
  },
  {
    id: "forest-23",
    prompt: "What is the square root of 64?",
    options: ["6", "7", "8", "9"],
    answerIndex: 2,
    category: "Math",
  },
  {
    id: "forest-24",
    prompt: "Which algorithm uses a divide-and-conquer strategy?",
    options: [
      "Bubble sort",
      "Linear search",
      "Quick sort",
      "Selection sort",
    ],
    answerIndex: 2,
    category: "Computer Science",
  },
  {
    id: "forest-25",
    prompt: "What is the main language spoken in Spain?",
    options: ["Portuguese", "Spanish", "Italian", "French"],
    answerIndex: 1,
    category: "Geography",
  },
  {
    id: "forest-26",
    prompt: "Which organ pumps blood through the human body?",
    options: ["Lung", "Brain", "Heart", "Liver"],
    answerIndex: 2,
    category: "Science",
  },
  {
    id: "forest-27",
    prompt: "Which keyword declares a constant in JavaScript?",
    options: ["let", "var", "const", "static"],
    answerIndex: 2,
    category: "Web",
  },
  {
    id: "forest-28",
    prompt: "Who wrote 'The Hobbit'?",
    options: [
      "J.R.R. Tolkien",
      "C.S. Lewis",
      "George Orwell",
      "Ernest Hemingway",
    ],
    answerIndex: 0,
    category: "Literature",
  },
  {
    id: "forest-29",
    prompt: "What is 12 multiplied by 8?",
    options: ["84", "96", "108", "112"],
    answerIndex: 1,
    category: "Math",
  },
  {
    id: "forest-30",
    prompt: "Which data structure uses Last-In, First-Out order?",
    options: ["Queue", "Array", "Stack", "Graph"],
    answerIndex: 2,
    category: "Computer Science",
  },
];
