import type { Question } from "./types";

export const defaultBattleQuestions: Question[] = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which data structure follows First-In, First-Out order?",
    correct_answer: "Queue",
    incorrect_answers: ["Stack", "Tree", "Graph"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the capital city of Japan?",
    correct_answer: "Tokyo",
    incorrect_answers: ["Seoul", "Kyoto", "Osaka"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science & Nature",
    question: "Which planet is known as the Red Planet?",
    correct_answer: "Mars",
    incorrect_answers: ["Venus", "Mercury", "Jupiter"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "What does CSS stand for?",
    correct_answer: "Cascading Style Sheets",
    incorrect_answers: [
      "Creative Style Sheets",
      "Computer Styled Syntax",
      "Colorful Sheet System",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "Which number is a prime number?",
    correct_answer: "29",
    incorrect_answers: ["21", "27", "33"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Entertainment: Books",
    question: "Who wrote Romeo and Juliet?",
    correct_answer: "William Shakespeare",
    incorrect_answers: ["Charles Dickens", "Jane Austen", "Mark Twain"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What is the result of 9 x 7?",
    correct_answer: "63",
    incorrect_answers: ["56", "72", "81"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science & Nature",
    question: "Which gas do humans breathe in to survive?",
    correct_answer: "Oxygen",
    incorrect_answers: ["Carbon dioxide", "Nitrogen", "Hydrogen"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which HTML tag is used for the largest heading by default?",
    correct_answer: "<h1>",
    incorrect_answers: ["<heading>", "<h6>", "<header>"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science & Nature",
    question: "What is the boiling point of water at sea level?",
    correct_answer: "100 degrees Celsius",
    incorrect_answers: [
      "90 degrees Celsius",
      "110 degrees Celsius",
      "120 degrees Celsius",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question:
      "Which sorting algorithm repeatedly swaps adjacent out-of-order elements?",
    correct_answer: "Bubble sort",
    incorrect_answers: ["Merge sort", "Quick sort", "Heap sort"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "Which ocean is the largest on Earth?",
    correct_answer: "Pacific Ocean",
    incorrect_answers: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "What does CPU stand for?",
    correct_answer: "Central Processing Unit",
    incorrect_answers: [
      "Computer Power Utility",
      "Central Program Usage",
      "Control Processing User",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "Which country is famous for the city of Cairo?",
    correct_answer: "Egypt",
    incorrect_answers: ["Turkey", "Morocco", "Greece"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What is 15 + 27?",
    correct_answer: "42",
    incorrect_answers: ["40", "41", "43"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science & Nature",
    question: "Which part of the plant usually absorbs water from soil?",
    correct_answer: "Root",
    incorrect_answers: ["Leaf", "Flower", "Stem"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which language is primarily used to style web pages?",
    correct_answer: "CSS",
    incorrect_answers: ["HTML", "SQL", "Python"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Entertainment: Books",
    question: "Who is the author of Pride and Prejudice?",
    correct_answer: "Jane Austen",
    incorrect_answers: ["Emily Bronte", "Mary Shelley", "Virginia Woolf"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "Which number is divisible by both 2 and 3?",
    correct_answer: "18",
    incorrect_answers: ["14", "25", "27"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science & Nature",
    question: "What do bees primarily collect from flowers?",
    correct_answer: "Nectar",
    incorrect_answers: ["Sand", "Dew", "Bark"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which HTML tag is commonly used to create a hyperlink?",
    correct_answer: "<a>",
    incorrect_answers: ["<link>", "<p>", "<href>"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "Which continent is Brazil located in?",
    correct_answer: "South America",
    incorrect_answers: ["Africa", "Europe", "Asia"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What is the square root of 64?",
    correct_answer: "8",
    incorrect_answers: ["6", "7", "9"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "Which algorithm uses a divide-and-conquer strategy?",
    correct_answer: "Quick sort",
    incorrect_answers: ["Bubble sort", "Linear search", "Selection sort"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Geography",
    question: "What is the main language spoken in Spain?",
    correct_answer: "Spanish",
    incorrect_answers: ["Portuguese", "Italian", "French"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science & Nature",
    question: "Which organ pumps blood through the human body?",
    correct_answer: "Heart",
    incorrect_answers: ["Lung", "Brain", "Liver"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which keyword declares a constant in JavaScript?",
    correct_answer: "const",
    incorrect_answers: ["let", "var", "static"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Entertainment: Books",
    question: "Who wrote The Hobbit?",
    correct_answer: "J.R.R. Tolkien",
    incorrect_answers: ["C.S. Lewis", "George Orwell", "Ernest Hemingway"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What is 12 multiplied by 8?",
    correct_answer: "96",
    incorrect_answers: ["84", "108", "112"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "Which data structure uses Last-In, First-Out order?",
    correct_answer: "Stack",
    incorrect_answers: ["Queue", "Array", "Graph"],
  },
];
