import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <section className="flex min-h-screen items-center justify-center bg-black p-4">
          <div
            className="aspect-video w-full overflow-hidden bg-black shadow-2xl"
            style={{
              maxWidth:
                "min(calc(100vw - 2rem), calc((100vh - 2rem) * 16 / 9))",
            }}
          >
            <div className="h-full w-full">{children}</div>
          </div>
        </section>
      </body>
    </html>
  );
}
